#!/usr/bin/env zsh
#
# Copyright (c) 2016 Dyne.org Foundation
# libdevuansdk is written and maintained by Ivan J. <parazyd@dyne.org>
# with code contributions from KatolaZ <katolaz@freaknet.org>
#                          and Jaromil <jaromil@dyne.org>
#
# This file is part of libdevuansdk
#
# This source code is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this source code. If not, see <http://www.gnu.org/licenses/>.

## libdevuansdk configuration

vars+=(release version mirror section)
arrs+=(core_packages base_packages system_packages)

os="devuan"
release="jessie"
version="1.0.0-beta"
mirror="http://packages.devuan.org/merged"
section="main"

core_packages=(
	devuan_keyring
	debian_keyring
	initramfs-tools
	binutils
	ca-certificates
	curl
	console-common
	less
	nano
	vi
)

base_packages=(
	bzip2
	dialog
	apt-utils
	fakeroot
	e2fsprogs
	parted
)

system_packages=(
	sysvinit
	ssh
)
