#!/usr/bin/env zsh
# shellcheck shell=bash
# Copyright (c) 2016-2021 Ivan J. <parazyd@dyne.org>
# This file is part of libdevuansdk
#
# This source code is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this source code. If not, see <http://www.gnu.org/licenses/>.

vars+=(libdevuansdk_version LIBPATH)

libdevuansdk_version="2.0"
LIBPATH="${LIBPATH:-$(dirname $0)}"

source "$LIBPATH/config"
source "$LIBPATH/zlibs/bootstrap"
source "$LIBPATH/zlibs/helpers"
source "$LIBPATH/zlibs/imaging"
source "$LIBPATH/zlibs/iso"
source "$LIBPATH/zlibs/vm"
source "$LIBPATH/zlibs/sysconf"

setopt pushdsilent

act "libdevuansdk v$libdevuansdk_version loaded"
