#!/usr/bin/env zsh
#
# Copyright (c) 2016 Dyne.org Foundation
# libdevuansdk is written and maintained by
#     Jaromil <jaromil@dyne.org>
#     KatolaZ <katolaz@freaknet.org>
#     parazyd <parazyd@dyne.org>
#
# This file is part of libdevuansdk
#
# This source code is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this source code. If not, see <http://www.gnu.org/licenses/>.


kernel_x86_install_default(){
	fn kernel_x86_install_default $@
	req=(strapdir os release version arch)
    root=$strapdir
	freq=($root/.done)
	reqck || return 1

	local kernel_base=linux-image
	local kernel=""

	case $arch in
		amd64)
			kernel=${kernel_base}-amd64
			;;
		i386)
			kernel=${kernel_base}-586
			;;
		*)
			error "Architecture ::1 arch:: is not supported!!!" ${arch}
			zerr; zshexit
			;;
	esac

	notice "Installing stock kernel for ::1 arch:: (::2 kernel::)" $arch $kernel

	mountdevprocsys ${root}

	sudo chroot ${root} apt-get --yes --force-yes --no-install-recommends install $kernel

	umountdevprocsys ${root}
	notice "default kernel installed"
}
