#!/usr/bin/env zsh
# Copyright (c) 2016-2017 Dyne.org Foundation
# libdevuansdk is maintained by Ivan J. <parazyd@dyne.org>
#
# This file is part of libdevuansdk
#
# This source code is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this source code. If not, see <http://www.gnu.org/licenses/>.

## all windows users are suckers

build_kernel_${arch} {
	fn build_kernel_${arch}
	req=(strapdir arch)
	ckreq || return 1

	local kernel_base="linux-image"
	case "$arch" in
		amd64) local kernel="${kernel_base}-amd64";;
		i386)  local kernel="${kernel_base}-586";;
	esac

	notice "installing stock kernel for $arch"

	cat <<EOF | sudo tee ${strapdir}/install-linux
#!/bin/sh
apt-get --yes --force-yes install ${kernel}
EOF
	chroot-script -d install-linux || zerr
}
