#!/usr/bin/env zsh
#
# Copyright (c) 2016 Dyne.org Foundation
# libdevuansdk is written and maintained by
#     Jaromil <jaromil@dyne.org>
#     KatolaZ <katolaz@freaknet.org>
#     parazyd <parazyd@dyne.org>
#
# This file is part of libdevuansdk
#
# This source code is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this source code. If not, see <http://www.gnu.org/licenses/>.


pkg_install_chroot(){
	fn pkg_install_chroot $@

	pkg_name=$1
    root=${2:-$strapdir}
	req=(pkg_name root)
	reqck || return 1

	mountdevprocsys ${root}

	sudo chroot ${root} apt-get --yes --force-yes install $kernel

	umountdevprocsys ${root}

	
}


pkg_install_ssh(){
	

}


pkg_remove_chroot(){


}


pkg_remove_ssh(){

	
}


pkg_set_package_list(){


}
