#!/usr/bin/env zsh
# Copyright (c) 2016-2017 Dyne.org Foundation
# libdevuansdk is maintained by Ivan J. <parazyd@dyne.org>
#
# This file is part of libdevuansdk
#
# This source code is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this source code. If not, see <http://www.gnu.org/licenses/>.

## ilpd

rsync_to_raw_image() {
	fn rsync_to_raw_image
	req=(workdir strapdir bootpart rootpart)
	ckreq || return 1

	notice "Preparing to rsync and tar the rootfs..."
	image_raw_mount
	silly sleep 1

	mkdir -p $R/dist
	pushd $strapdir
		tar_strapdir || zerr

		notice "rsyncing strapdir to raw image..."
		sudo rsync -HPavz -q ./* $workdir/mnt || {
			image_raw_umount
			die "not enough space, please report a bug"
			zerr
		}
	popd

	image_raw_umount
}
